from SequenceTools import SequenceTools

tools = SequenceTools()
tools.importSeqeuenceByNCBIIdentifier("AK079513.1")
tools.deconstructImportedCDNASequence(tools.allSequences["AK079513.1"], "AK079513.1")
tools.makeNewDeconstructedSequenceFromDeconstructedSequencePeptideRange(tools.allDeconstructedSequences["AK079513.1"], 24, 244, "CD86_Extracellular")
dnaSeq = tools.returnDnaSequenceFromDeconstructedList(tools.allDeconstructedSequences["CD86_Extracellular"]['deconstructedList'])
dnaSeq2 = tools.createSeqObjectFromString("GTTTCCGTGGAGACGCAAGCTTATTTCAATGGGACTGCATATCTGCCGTGCCCAT TTACAAAGGCTCAAAACATAAGCCTGAGTGAGCTGGTAGTATTTTGGCAGGACCAGCAAA AGTTGGTTCTGTACGAGCACTATTTGGGCACAGAGAAACTTGATAGTGTGAATGCCAAGT ACCTGGGCCGCACGAGCTTTGACAGGAACAACTGGACTCTACGACTTCACAATGTTCAGA TCAAGGACATGGGCTCGTATGATTGTTTTATACAAAAAAAGCCACCCACAGGATCAATTA TCCTCCAACAGACATTAACAGAACTGTCAGTGATCGCCAACTTCAGTGAACCTGAAATAA AACTGGCTCAGAATGTAACAGGAAATTCTGGCATAAATTTGACCTGCACGTCTAAGCAAG GTCACCCGAAACCTAAGAAGATGTATTTTCTGATAACTAATTCAACTAATGAGTATGGTG ATAACATGCAGATATCACAAGATAATGTCACAGAACTGTTCAGTATCTCCAACAGCCTCT CTCTTTCATTCCCGGATGGTGTGTGGCATATGACCGTTGTGTGTGTTCTGGAAACGGAGT CAATGAAGATTTCCTCCAAACCTCTCAATTTCACTCAAGAGTTTCCATCTCCTCAAACGT ATTGGAAG")
dnaSeq3 = tools.createSeqObjectFromString("GTTTCCGTGGAGACGCAAGCTTATTTCAATGGGACTGCATATCTGCCGTGCCCAT TTACAAAGGCTCAAAACATAAGCCTGAGTGAGCTGGTAGTATTTTGGCAGGACCAGCAAA AGTTGGTTCTGTACGAGCACTATTTGGGCACAGAGAAACTTGATAGTGTGAATGCCAAGT ACCTGGGCCGCACGAGCTTTGACAGGAACAACTGGACTCTACGACTTCACAATGTTCAGA TCAAGGACATGGGCTCGTATGATTGTTTTATACAAAAAAAGCCACCCACAGGATCAATTA TCCTCCAACAGACATTAACAGAACTGTCAGTGATCGCCAACTTCAGTGAACCTGAAATAA AACTGGCTCAGAATGTAACAGGAAATTCTGGCATAAATTTGACCTGCACGTCTAAGCAAG GTCACCCGAAACCTAAGAAGATGTATTTTCTGATAACTAATTCAACTAATGAGTATGGTG ATAACATGCAGATATCACAAGATAATGTCACAGAACTGTTCAGTATCTCCAACAGCCTCT CTCTTTCATTCCCGGATGGTGTGTGGCATATGACCGTTGTGTGTGTTCTGGAAACGGAGT CAATGAAGATTTCCTCCAAACCTCTCAATTTCACTCAAGAGTTTCCATCTCCTCAAACGT ATTGGAAG")

comp = tools.compareSequence(dnaSeq, dnaSeq2)
comp2 = tools.compareSequence(dnaSeq, dnaSeq3)

nhe1Seq = tools.createSeqObjectFromString("GCTAGC")
tools.deconstructDNASequence(nhe1Seq, "NheI", False)

ecoR1Seq = tools.createSeqObjectFromString("GAATTC")
tools.deconstructDNASequence(ecoR1Seq, "EcoRI", False)

seqPeptideSeq = tools.createSeqObjectFromString("ATGGGGATCCTTCCCAGCCCTGGGATGCCTGCGCTGCTCTCCCTCGTGAGCCTTCTCTCCGTGCTGCTGATGGGTTGCGTAGCT")
tools.deconstructDNASequence(seqPeptideSeq, "SecretionSignal", True)

linker1Seq = tools.createSeqObjectFromString("GGTACC")
tools.deconstructDNASequence(linker1Seq, "Linker1", True)

linker2Seq = tools.createSeqObjectFromString("GGTAGTGGTGGTAGTGGT")
tools.deconstructDNASequence(linker2Seq, "Linker2", True)

apTagSeq = tools.createSeqObjectFromString("GGTCTGAATGATATTTTCGAAGCGCAGAAAATTGAATGGCATGAA")
tools.deconstructDNASequence(apTagSeq, "APTag", True)

linker3eq = tools.createSeqObjectFromString("GGTAGCGGA")
tools.deconstructDNASequence(linker3eq, "Linker3", True)

tevSeq = tools.createSeqObjectFromString("GAGAACCTATACTTCCAAGGA")
tools.deconstructDNASequence(tevSeq, "TEV", True)

hisTagSeq = tools.createSeqObjectFromString("CACCACCATCATCACCAC")
tools.deconstructDNASequence(hisTagSeq, "HIS", True)

stopCodonsSeq = tools.createSeqObjectFromString("TAGTAA")
tools.deconstructDNASequence(stopCodonsSeq, "STOPS", True)

tools.createConstructFromDeconstructedSequences(['SecretionSignal', 'Linker1', 'CD86_Extracellular', "Linker2", 'APTag', 'Linker3', 'TEV', 'HIS','STOPS'], 'CD86Extracellular-APTag-TEV-HIS')
tools.createConstructFromDeconstructedSequences(['NheI' ,'SecretionSignal', 'Linker1', 'CD86_Extracellular', "Linker2", 'APTag', 'Linker3', 'TEV', 'HIS','STOPS', 'EcoRI'], 'NheI-CD86Extracellular-APTag-TEV-HIS-EcoRI')

fullSeq = tools.createSeqObjectFromString("ATGGGGATCCTTCCCAGCCCTGGGATGCCTGCGCTGCTCTCCCTCGTGAGCCTTCTCTCCGTGCTGCTGATGGGTTGCGTAGCTGGTACCGTTTCCGTGGAGACGCAAGCTTATTTCAATGGGACTGCATATCTGCCGTGCCCAT TTACAAAGGCTCAAAACATAAGCCTGAGTGAGCTGGTAGTATTTTGGCAGGACCAGCAAA AGTTGGTTCTGTACGAGCACTATTTGGGCACAGAGAAACTTGATAGTGTGAATGCCAAGT ACCTGGGCCGCACGAGCTTTGACAGGAACAACTGGACTCTACGACTTCACAATGTTCAGA TCAAGGACATGGGCTCGTATGATTGTTTTATACAAAAAAAGCCACCCACAGGATCAATTA TCCTCCAACAGACATTAACAGAACTGTCAGTGATCGCCAACTTCAGTGAACCTGAAATAA AACTGGCTCAGAATGTAACAGGAAATTCTGGCATAAATTTGACCTGCACGTCTAAGCAAG GTCACCCGAAACCTAAGAAGATGTATTTTCTGATAACTAATTCAACTAATGAGTATGGTG ATAACATGCAGATATCACAAGATAATGTCACAGAACTGTTCAGTATCTCCAACAGCCTCT CTCTTTCATTCCCGGATGGTGTGTGGCATATGACCGTTGTGTGTGTTCTGGAAACGGAGT CAATGAAGATTTCCTCCAAACCTCTCAATTTCACTCAAGAGTTTCCATCTCCTCAAACGTATTGGAAGGGTAGTGGTGGTAGTGGTGGTCTGAATGATATTTTCGAAGCGCAGAAAATTGAATGGCATGAAGGTAGCGGAGAGAACCTATACTTCCAAGGACACCACCATCATCACCAC TAGTAA")
fullPeptideSeq = tools.createSeqObjectFromString("M G I L P S P G M P A L L S L V S L L S V L L M G C V A G T V S V E T Q A Y F N G T A Y L P C P F T K A Q N I S L S E L V V F W Q D Q Q K L V L Y E H Y L G T E K L D S V N A K Y L G R T S F D R N N W T L R L H N V Q I K D M G S Y D C F I Q K K P P T G S I I L Q Q T L T E L S V I A N F S E P E I K L A Q N V T G N S G I N L T C T S K Q G H P K P K K M Y F L I T N S T N E Y G D N M Q I S Q D N V T E L F S I S N S L S L S F P D G V W H M T V V C V L E T E S M K I S S K P L N F T Q E F P S P Q T Y W K G S G G S G G L N D I F E A Q K I E W H E G S G E N L Y F Q G H H H H H H * *")

genScriptSeq = tools.createSeqObjectFromString("""GCTAGCATGGGGATCCTTCCCAGCCCTGGGATGCCTGCGCTGCTCTCCCTCGTGAGCCTTCTCTCCGTGCTGCTGATGGGTTGCGTAGCTGGTAC
CGTTTCCGTGGAGACGCAAGCTTATTTCAATGGGACTGCATATCTGCCGTGCCCATTTACAAAGGCTCAAAACATAAGCCTGAGTGAGCTGGTAGTATTT
TGGCAGGACCAGCAAAAGTTGGTTCTGTACGAGCACTATTTGGGCACAGAGAAACTTGATAGTGTGAATGCCAAGTACCTGGGCCGCACGAGCTTTGACA
GGAACAACTGGACTCTACGACTTCACAATGTTCAGATCAAGGACATGGGCTCGTATGATTGTTTTATACAAAAAAAGCCACCCACAGGATCAATTATCCT
CCAACAGACATTAACAGAACTGTCAGTGATCGCCAACTTCAGTGAACCTGAAATAAAACTGGCTCAGAATGTAACAGGAAATTCTGGCATAAATTTGACC
TGCACGTCTAAGCAAGGTCACCCGAAACCTAAGAAGATGTATTTTCTGATAACTAATTCAACTAATGAGTATGGTGATAACATGCAGATATCACAAGATA
ATGTCACAGAACTGTTCAGTATCTCCAACAGCCTCTCTCTTTCATTCCCGGATGGTGTGTGGCATATGACCGTTGTGTGTGTTCTGGAAACGGAGTCAAT
GAAGATTTCCTCCAAACCTCTCAATTTCACTCAAGAGTTTCCATCTCCTCAAACGTATTGGAAGGGTAGTGGTGGTAGTGGTGGTCTGAATGATATTTTC
GAAGCGCAGAAAATTGAATGGCATGAAGGTAGCGGAGAGAACCTATACTTCCAAGGACACCACCATCATCACCACTAGTAAGAATTC""")

comp3 = tools.compareDNAConstructToSequence(tools.allConstructs['CD86Extracellular-APTag-TEV-HIS'], fullSeq)
comp4 = tools.comparePeptideConstructToSequence(tools.allConstructs['CD86Extracellular-APTag-TEV-HIS'], fullPeptideSeq)
comp5 = tools.compareDNAConstructToSequence(tools.allConstructs['NheI-CD86Extracellular-APTag-TEV-HIS-EcoRI'], genScriptSeq)

pass