from SequenceTools import SequenceTools

tools = SequenceTools()

sars_cov2_ecto_mclellan = tools.create_seq_object_from_string(
    '''
    ATGTTCGTGTTCCTGGTGCTCCTGCCTCTGGTGAGCAGCCAGTGCGTGAACCTGACCACCCGAACCCAGCTCC
    CACCAGCCTACACCAACAGCTTTACACGGGGCGTGTACTACCCTGACAAGGTGTTCAGATCTAGCGTCCTGCA
    CAGCACTCAGGACCTCTTCCTGCCGTTCTTCAGCAACGTGACATGGTTCCACGCCATCCACGTGAGCGGCACA
    AACGGAACCAAGCGGTTTGATAACCCCGTCCTGCCATTCAATGATGGAGTTTACTTCGCCAGTACCGAGAAGA
    GTAACATCATCCGGGGCTGGATCTTCGGCACCACCCTGGATAGCAAAACACAGAGCCTCCTGATCGTGAACAA
    TGCCACGAACGTCGTGATCAAGGTGTGCGAGTTCCAGTTTTGCAATGATCCTTTCCTGGGTGTGTACTACCAC
    AAGAACAACAAGAGCTGGATGGAAAGCGAGTTCAGAGTCTACAGCAGCGCCAACAACTGCACATTCGAGTACG
    TCTCTCAGCCTTTTCTGATGGACCTTGAGGGGAAACAAGGCAACTTCAAGAACCTGAGAGAATTCGTGTTCAA
    GAACATCGACGGCTACTTCAAAATCTACTCCAAGCACACACCCATCAACCTGGTCCGGGACCTCCCTCAGGGC
    TTCAGCGCCCTGGAACCCCTGGTCGACCTGCCCATAGGCATCAACATAACGCGGTTCCAAACCCTGCTGGCCC
    TGCATAGATCCTACCTGACTCCTGGCGACAGCAGCAGCGGATGGACCGCCGGAGCTGCAGCCTACTATGTGGG
    CTACCTGCAACCTAGAACCTTCCTGCTGAAGTACAACGAGAACGGCACAATCACAGACGCCGTCGACTGCGCC
    CTGGACCCTCTCTCTGAGACAAAGTGCACCCTGAAGTCCTTCACCGTGGAAAAGGGCATCTACCAGACCAGCA
    ACTTCCGGGTGCAGCCTACAGAGAGCATCGTGCGATTTCCAAACATTACCAACCTCTGCCCCTTCGGCGAGGT
    GTTTAACGCCACAAGATTTGCCTCCGTTTACGCCTGGAATAGAAAGAGAATCAGCAATTGTGTGGCCGACTAC
    TCCGTGCTGTATAACAGCGCCTCTTTCAGCACCTTCAAGTGCTACGGCGTTTCCCCAACAAAGCTGAATGACC
    TGTGCTTCACCAACGTGTACGCCGACTCCTTCGTAATTAGAGGCGATGAGGTGCGGCAGATCGCACCAGGCCA
    GACCGGTAAGATCGCTGACTACAACTATAAGCTGCCTGATGATTTTACAGGCTGCGTGATCGCCTGGAACTCT
    AACAACCTGGATAGCAAGGTGGGCGGCAACTACAACTACCTGTACCGGCTGTTTCGCAAGTCTAACCTGAAAC
    CTTTCGAGAGAGACATCTCCACAGAGATCTACCAGGCCGGTTCTACACCTTGTAACGGGGTGGAAGGCTTCAA
    CTGTTACTTCCCTCTGCAAAGCTACGGCTTCCAGCCTACCAATGGAGTCGGCTACCAGCCATACCGGGTGGTC
    GTGCTGTCCTTCGAGTTACTCCACGCCCCCGCCACCGTCTGCGGTCCTAAGAAGTCCACCAATCTGGTTAAGA
    ACAAATGCGTGAACTTCAACTTCAACGGCCTGACCGGGACCGGCGTGCTGACCGAAAGCAACAAAAAGTTCCT
    CCCCTTCCAGCAGTTCGGCCGTGATATCGCTGACACCACAGATGCCGTCAGAGATCCACAGACCCTGGAAATC
    CTGGATATTACACCCTGCTCCTTCGGAGGAGTTTCTGTGATCACCCCCGGGACCAATACCAGCAACCAGGTGG
    CTGTGCTGTACCAAGATGTTAACTGCACCGAGGTTCCTGTGGCCATCCACGCCGATCAGCTGACACCTACTTG
    GAGAGTGTACTCCACTGGCTCCAATGTGTTCCAGACCAGGGCCGGATGTCTGATCGGCGCCGAGCACGTGAAT
    AACAGTTACGAGTGCGACATCCCTATCGGCGCCGGCATCTGTGCCAGCTACCAGACCCAGACAAACAGCCCTG
    GGTCTGCTTCCTCTGTAGCTAGCCAGAGCATCATCGCCTACACCATGAGCCTGGGCGCAGAGAACAGCGTGGC
    CTATTCCAACAACTCTATCGCCATTCCCACCAACTTTACAATTAGCGTCACAACAGAGATCCTGCCCGTGAGC
    ATGACCAAGACCAGCGTGGACTGTACAATGTACATCTGTGGCGACAGCACTGAATGCAGCAACCTGCTGCTGC
    AATACGGCTCCTTTTGCACCCAACTGAACCGGGCGCTGACCGGAATCGCCGTGGAACAGGACAAAAATACCCA
    GGAGGTGTTCGCCCAAGTGAAGCAGATCTACAAGACCCCACCTATCAAGGACTTCGGCGGCTTTAACTTTAGC
    CAGATTCTCCCTGATCCTTCTAAGCCTAGCAAGCGGAGCTTTATCGAGGATCTGCTGTTCAACAAGGTCACCC
    TGGCCGATGCCGGCTTTATCAAACAGTATGGCGATTGCCTGGGCGACATAGCCGCCAGAGATCTGATCTGCGC
    CCAGAAATTCAACGGCCTGACAGTTCTCCCACCTCTGCTGACCGACGAGATGATCGCTCAGTACACCTCTGCC
    CTGCTGGCTGGCACCATCACATCTGGGTGGACATTTGGCGCCGGCGCCGCCCTGCAGATCCCCTTTGCCATGC
    AGATGGCCTATAGATTCAACGGAATCGGCGTGACCCAGAACGTGCTGTATGAAAACCAGAAGCTGATCGCTAA
    CCAGTTCAATTCTGCCATCGGCAAGATCCAGGACTCCCTCTCCTCTACCGCCAGCGCCCTGGGCAAACTGCAG
    GACGTGGTGAATCAGAACGCCCAAGCCCTGAACACCCTGGTGAAGCAGCTCAGCAGCAATTTTGGCGCCATCA
    GCTCTGTGCTGAACGATATCCTGTCTAGACTGGACCCTCCAGAAGCCGAAGTCCAGATCGATAGACTGATCAC
    AGGCAGACTGCAGTCCCTGCAAACCTACGTGACCCAACAGCTGATCAGGGCCGCTGAAATAAGAGCCAGCGCC
    AATCTCGCCGCTACCAAGATGTCCGAGTGTGTGCTGGGACAGTCTAAACGCGTTGACTTCTGCGGCAAAGGCT
    ATCACCTGATGAGCTTCCCCCAGAGCGCGCCGCACGGCGTGGTGTTCCTGCATGTGACATACGTGCCTGCCCA
    AGAGAAGAATTTCACAACCGCCCCTGCCATCTGCCACGACGGCAAGGCCCACTTCCCAAGAGAGGGCGTTTTC
    GTTTCCAATGGCACACACTGGTTCGTGACACAAAGAAACTTCTACGAACCCCAGATTATCACCACCGACAACA
    CCTTCGTGAGTGGCAATTGTGACGTGGTCATCGGAATCGTGAACAACACAGTGTACGACCCTCTGCAACCTGA
    GCTGGACTCTTTTAAGGAAGAGCTGGACAAGTACTTTAAAAACCACACCAGCCCCGATGTGGACCTGGGCGAC
    ATCAGTGGCATTAACGCCAGCGTGGTGAACATCCAAAAGGAAATCGACAGACTGAACGAGGTGGCCAAGAACC
    TGAACGAGTCCCTGATCGACCTGCAGGAGCTCGGCAAATACGAGCAG
    '''
)

linker_1_mclellan = tools.create_seq_object_from_string(
    '''
    GGATCCGGA
    '''
)

t4_fibritin_trimerization_motif = tools.create_seq_object_from_string(
    '''
    TACATCCCCGAGGCCCCCAGAGATGGCCAGGCCTACGTGCGGAAGGACGGCGAGTGGGTACTGCTGAGCACATTCCTGGGC
    '''
)

linker_2_mclellan = tools.create_seq_object_from_string(
    '''
    AGATCC
    '''
)

hrv3c_protease_clevage_site = tools.create_seq_object_from_string(
    '''
    CTGGAGGTGCTGTTCCAGGGCCCA
    '''
)

linker_3_mclellan = tools.create_seq_object_from_string(
    '''
    GGC
    '''
)

eight_x_his_tag = tools.create_seq_object_from_string(
    '''
    CATCACCACCATCACCACCATCAT
    '''
)

linker_4_mclellan = tools.create_seq_object_from_string(
    '''
    AGCGCC
    '''
)

twin_strept_2_tag = tools.create_seq_object_from_string(
    '''
    TGGTCCCACCCCCAGTTCGAGAAGGGCGGCGGTAGTGGAGGGGGCGGATCTGGCGGCTCAGCTTGGAGCCACCCCCAGTTCGAAAAG
    '''
)

stop_3 = tools.create_seq_object_from_string(
    '''
    TGATAATGA
    '''
)

tools.deconstruct_dna_sequence(sars_cov2_ecto_mclellan, "SarsCov2EctoMclellan", True)
tools.deconstruct_dna_sequence(stop_3, 'end_to_hind_3', True)
test_seq = tools.all_constructs["SarsCov2EctoMclellan"]['peptideSequence'][986:990]
tools.make_new_deconstructed_sequence_from_construct_sequence_with_peptide_mutation(tools.all_constructs["SarsCov2EctoMclellan"], 'CD80_I68D', 68, 'I', 'D')
pass